-- MySQL Script generated by MySQL Workbench
-- Sun Dec 30 10:33:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TypeUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeUser` (
  `idTypeUser` CHAR(6) NOT NULL,
  `NameOfType` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` CHAR(6) NOT NULL,
  `FullName` VARCHAR(45) NULL,
  `DoB` DATE NULL,
  `School` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `TypeUser_idTypeUser` CHAR(6) NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_TypeUser1_idx` (`TypeUser_idTypeUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `mydb`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` CHAR(10) NOT NULL,
  `CourseName` VARCHAR(45) NULL,
  `NumberOfLession` INT NULL,
  PRIMARY KEY (`idCourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserRecord` (
  `Course_idCourse` CHAR(10) NOT NULL,
  `User_idUser` CHAR(6) NOT NULL,
  `Lession` INT NOT NULL,
  `Point` FLOAT NULL,
  PRIMARY KEY (`Course_idCourse`, `User_idUser`, `Lession`),
  INDEX `fk_UserRecord_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_UserRecord_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  CONSTRAINT `fk_UserRecord_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserRecord_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topic` (
  `idTopic` CHAR(10) NOT NULL,
  `Topic'sName` VARCHAR(45) NULL,
  PRIMARY KEY (`idTopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TopicSharing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TopicSharing` (
  `idTopicSharing` CHAR(10) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `DateUpload` DATE NULL,
  `Author` VARCHAR(45) NULL,
  `Link` VARCHAR(100) NULL,
  `Description` VARCHAR(500) NULL,
  `Topic_idTopic` CHAR(10) NOT NULL,
  PRIMARY KEY (`idTopicSharing`),
  INDEX `fk_TopicSharing_Topic1_idx` (`Topic_idTopic` ASC) VISIBLE,
  CONSTRAINT `fk_TopicSharing_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `mydb`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CodeDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CodeDetail` (
  `UserRecord_Course_idCourse` CHAR(10) NOT NULL,
  `UserRecord_User_idUser` CHAR(6) NOT NULL,
  `UserRecord_Lession` INT NOT NULL,
  `LinkContent` VARCHAR(9999) NULL,
  `Comment` VARCHAR(200) NULL,
  `State` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`UserRecord_Course_idCourse`, `UserRecord_User_idUser`, `UserRecord_Lession`),
  INDEX `fk_CodeDetail_UserRecord1_idx` (`UserRecord_Course_idCourse` ASC, `UserRecord_User_idUser` ASC, `UserRecord_Lession` ASC) VISIBLE,
  CONSTRAINT `fk_CodeDetail_UserRecord1`
    FOREIGN KEY (`UserRecord_Course_idCourse` , `UserRecord_User_idUser` , `UserRecord_Lession`)
    REFERENCES `mydb`.`UserRecord` (`Course_idCourse` , `User_idUser` , `Lession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Score` (
  `User_idUser` CHAR(6) NOT NULL,
  `Score` INT NULL,
  INDEX `fk_Rank_User1_idx` (`User_idUser` ASC) VISIBLE,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Rank_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `User_idUser` CHAR(6) NOT NULL,
  `UserName` VARCHAR(45) NULL,
  `PassWord` VARCHAR(45) NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Account_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Privilege` (
  `TypeUser_idTypeUser` CHAR(6) NOT NULL,
  `Post` BINARY NULL,
  `Read` BINARY NULL,
  `Write` BINARY NULL,
  `Delete` BINARY NULL,
  PRIMARY KEY (`TypeUser_idTypeUser`),
  CONSTRAINT `fk_Privilege_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `mydb`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CourseDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CourseDetail` (
  `Course_idCourse` CHAR(10) NOT NULL,
  `LessionName` VARCHAR(45) NULL,
  `Order` INT NULL,
  CONSTRAINT `fk_CourseDetail_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
